extends:
  - chartjs
  - esnext

env:
  es6: true
  browser: true
  node: true

parserOptions:
  ecmaVersion: 7
  sourceType: module
  ecmaFeatures:
    impliedStrict: true
    modules: true
    experimentalObjectRestSpread: true

plugins: ['html']

rules:
  class-methods-use-this: 0
  no-empty-function: 0
  complexity: [1, 10]
  max-statements: [1, 30]
